### ISSUE TITLE
Installation on Linux

### ISSUE THREAD

**Issue by eik3** [adammck/terraform-inventory#12]
I'm on Ubuntu, what would be the steps basically?

**Comment by adammck** [comment]
I don't currently provide a Linux binary or package, so you'll have to built it yourself for now. If you're not familiar with Go, there are lots of good tutorials available. I'll leave this issue open as a reminder to add a Linux distribution.

**Comment by proffalken** [comment]
To install:

```apt-get install gccgo-go
git clone git@github.com:adammck/terraform-inventory.git
cd terraform-inventory
go build
cp terraform-inventory <path/to/your/terraform/installation>```

I've then created a file in <ansible_repo/bin> called "tfi" with the following content:
```#!/bin/bash
terraform-inventory --list
```

and finally I've configured my ansible.cfg file with

```
[defaults]
inventory = bin/tfi
```

HTH,

Matt

**Comment by adammck** [comment]
Thanks, Matt! I've just released [v0.5](https://github.com/adammck/terraform-inventory/releases/tag/v0.5), which includes Linux builds. Would one of you mind testing them out?

**Comment by eik3** [comment]
Tried them out on my amd64 notebook, i386 virtual server and ARM RasPi, all worked.

One thing though: `.tar.gz` is preferred over `.zip` in the linux world.

**Comment by adammck** [comment]
Thanks for testing! Good point about the format, I'l switch to tar.gz for the next release. I was just being lazy when writing the release script.

**Comment by proffalken** [comment]
Sorry I didn't get a chance to test this, its been a busy few weeks.

I'll give it a go and let you know shortly
