### ISSUE TITLE
Ansible HostGroup Support

### ISSUE THREAD

**Issue by proffalken** [adammck/terraform-inventory#16]
At present there doesn't appear to be a way to output the data from terraform as Ansible Host Groups to allow for multiple hosts to be configured via a single play.

For example, a play that starts with "hosts: webservers" doesn't know that "aws_instance.webserver.0" should belong to the "webservers" ansible group.

It would be nice to have some way of mapping aws_instance.webserver.* to a group or similar.

**Comment by adammck** [comment]
Yes, this would be very useful, especially when multiple identical resources are created with Terraform's `count` parameter. They should all be returned as a single host group.

**Comment by kvz** [comment]
+1

**Comment by afritzler** [comment]
+1

**Comment by girvo** [comment]
+1

**Comment by afritzler** [comment]
+1

**Comment by zihaoyu** [comment]
+1

**Comment by jackspirou** [comment]
Working on a little patch with @jbehling that should help with this.  You can find it here https://github.com/adammck/terraform-inventory/compare/master...jackspirou:master

The idea is that `metadata.groups` would be string of comma separated groups that would be parsed upon the `--list` flag.  So values like `"metadata.groups": "mongosc,mongos,mongoc",` might produce something like the following output: 

```JSON
{
  "mongoc":["10.10.10.101","10.10.10.102","10.10.10.103"],
  "mongos":["10.10.10.101","10.10.10.102","10.10.10.103"],
  "mongosc":["10.10.10.101","10.10.10.102","10.10.10.103"],
  "server.0":["10.10.10.101"],
  "server.1":["10.10.10.102"],
  "server.2":["10.10.10.103"]
}
```

**Comment by jackspirou** [comment]
@adammck Let me and @jbehling know what you think of PR #21 and if it helps solve this issue.

**Comment by vasiliyb** [comment]
+1

**Comment by adammck** [comment]
Please check out #22 for an implementation of this. Feedback would be very much appreciated.

**Comment by johnwards** [comment]
@adammck So glad I found this today :) I'm just doing some elasticsearch stuff with terraform and ansible so needed groups. 

Works perfectly, however just an FYI from terraform that you'll need to come up with a different strategy for naming things.

    Warnings:
      * aws_instance.eip-elasticsearch.2: eip-elasticsearch.2: resource name can only contain letters, numbers, dashes, and underscores.
    This will be an error in Terraform 0.4
      * aws_instance.eip-elasticsearch.1: eip-elasticsearch.1: resource name can only contain letters, numbers, dashes, and underscores.
    This will be an error in Terraform 0.4

**Comment by adammck** [comment]
Thanks for the heads up, @johnwards! I don't entirely understand the warning, since those resource names -- something.index -- were presumably generated by Terraform itself, via the `count` param. Or perhaps it's specific to your templates?

**Comment by johnwards** [comment]
Ah, so this might be my problem I guess. I directly named my ec2 instances:

    resource "aws_instance" "eip-elasticsearch.1"

    resource "aws_instance" "eip-elasticsearch.2"

So in this case this is my bad for not realising there is a count param and putting it in manually, but I do think that having instances of different settings (security groups, instance size etc) but in the same group is probably a valid use case and you could achieve it this way?
