### ISSUE TITLE
--inventory-file=terraform-inventory does not yield hosts

### ISSUE THREAD

**Issue by kevinlondon** [adammck/terraform-inventory#29]
Following the README currently does not find the proper executable script for inventory. Instead, I found I had to use `which terraform-inventory` to reverse the path of the executable. Here's some example output (which has been trimmed):

```
$ terraform-inventory --list
{"db":["54.208.224.51"], . . . }
$ ansible -i terraform-inventory all -m ping
[WARNING]: provided hosts list is empty, only localhost is available

$ ansible -i `which terraform-inventory` all -m ping
54.208.224.51 | . . .
```

I'm on Ansible 2.0.0.2 currently.

**Comment by adammck** [comment]
Oops! Sorry about that. Thanks for reporting.

**Comment by andrefbsantos** [comment]
I'm currently experiencing the same issue.

**Comment by nballotta** [comment]
Hi @adammck, any plan to fix this?

**Comment by adammck** [comment]
Yes, thanks for the reminder, @nballotta. I think this is just a documentation bug, right? It seems like ansible requires the full path to the dynamic inventory executable rather than searching the $PATH.

**Comment by nballotta** [comment]
@adammck oh yes! Sorry I noticed now that with full path currently works :)
