### ISSUE TITLE
Any plans for support for Digitalocean?

### ISSUE THREAD

**Issue by tayzlor** [adammck/terraform-inventory#3]
At the moment AWS is hard-wired in. An example digitalocean droplet terraform state file the values are slightly different (in terms of IP address etc..) e.g. - 

```
"digitalocean_droplet.test": {
    "type": "digitalocean_droplet",
    "primary": {
        "id": "4597742",
        "attributes": {
            "id": "4597742",
            "image": "11137507",
            "ipv4_address": "46.111.41.144",
            "locked": "false",
            "name": "test-0",
            "region": "lon1",
            "size": "512mb",
            "ssh_keys.#": "1",
            "ssh_keys.0": "54:0r:91:05:db:b7:7f:47:ba:3b:w2:7e:8u:dc:5d:45",
            "status": "active"
        }
    }
}
```

**Comment by adammck** [comment]
Thanks for raising this. I should be clearer in the README that only AWS is currently supported. I don't have any immediate plans to add support for other providers, but I do consider it a bug. It should be reasonably simple to fix, if you're interested in doing so.

**Comment by adammck** [comment]
**Update**: [v0.4](https://github.com/adammck/terraform-inventory/releases/tag/v0.4) includes DigitalOcean support.
