### ISSUE TITLE
create new release

### ISSUE THREAD

**Issue by thecodeassassin** [adammck/terraform-inventory#34]
Dear @adammck ,

Version 0.6 does not feature the required change to get the correct ip address or GCE. Can you create a new release with the lastest changes?

Thanks!

**Comment by adammck** [comment]
Just released [v0.6.1](https://github.com/adammck/terraform-inventory/releases/tag/v0.6.1) with the fix. Please let me know if that solves your problem.

**Comment by thecodeassassin** [comment]
that should do it yes, thanks!
