### ISSUE TITLE
Use private IP, not public IP?

### ISSUE THREAD

**Issue by completerevolution** [adammck/terraform-inventory#38]
Is it possible to extract the private IP, instead of public IP?  I'm using TF + TF-Inventory, but accessing the servers via a bastion host.  It's been a very useful tool so far, thanks!

**Comment by completerevolution** [comment]
I don't know anything about Go, but a quick poke around, and removing the 'public_ip' option in 'resources.go' did the trick :-)

**Comment by fntlnz** [comment]
@completerevolution Editing the source code is not the best option for your need.
What you want to do is:

```
export TF_KEY_NAME=private_ip
```

and then the inventory will output private ips instead of public ones.

**Comment by dduong26** [comment]
I tried:

`export TF_KEY_NAME=private_ip`

and it didn't work for me.  I got a blank list.  However, as of version 0.7.7, if I did this:

`export TF_KEY_NAME=ipv4_address_private`

It worked fine.
