### ISSUE TITLE
Inventory spot instances?

### ISSUE THREAD

**Issue by cbarbour** [adammck/terraform-inventory#39]
Would it be possible for terraform-inventory to include spot instances in the inventory? Specifically, when a spot request is fulfilled, is there any way to discover the IP of the resulting instance?

**Comment by cbarbour** [comment]
Nevermind. I failed to refresh my state before checking the inventory. I'm very happy and impressed with this tool.

**Comment by adammck** [comment]
Glad to be of service. Please do open another issue if you notice anything regarding spot instances which isn't working. I don't use them myself, so they're not very well tested.
