### ISSUE TITLE
Add --public/--private flags to specify which IP to return

### ISSUE THREAD

**Issue by adammck** [adammck/terraform-inventory#4]
Right now we only return the `private_ip` of each instance, but it would be useful to be able to return the public IP instead, or even to correlate instances with their DNS records if possible.

**Comment by adammck** [comment]
We now return the public IP if available, otherwise the private IP. Close enough.

**Comment by rposborne** [comment]
@adammck how would you go about getting around networking requirements that prevent access from the public ip.   Is there anyway to force private only?

**Comment by adammck** [comment]
I'm afraid that there's currently no way to force a private IP when a public IP is available. I'd like to add a flag and/or ENV var to do it.

**Comment by anarcher** [comment]
I like it! very useful for me. :-)

IMO, If the terraform-inventory returns both of public IPs and private IPs, It's more useful for me. 

``` instance_private : ["10.1.1.1"] , instance : [ "52.3.x.x"] ```

What do you think?

**Comment by kunickiaj** [comment]
We usually address instances by private ip (site to site vpn) even though they also have public IPs assigned usually.

**Comment by trevorr** [comment]
You can force use of the private IP by setting `TF_KEY_NAME`. For example:

```
TF_KEY_NAME=private_ip ansible-playbook --inventory-file=`which terraform-inventory` ansible/consul.yml
```
