### ISSUE TITLE
Use .terraform/terraform.tfstate when local state is unavailable

### ISSUE THREAD

**Issue by cbarbour** [adammck/terraform-inventory#40]
## Description
Feature request.

Currently, terraform inventory checks the current working directory for the `terraform.tfstate` file. When configured to use a remote state, terraform places the state file in the `.terraform/` directory instead.

It would be useful for terraform-inventory to check for `.terraform/terraform.tfstate` if it doesn't find the state in the root of the terraform configuration. This would make life simpler for folks using remote state, and might help avoid the need to wrap terraform-inventory to pull state from a s3 bucket or other remote location.

## Steps to reproduce
1. Create a S3 bucket for remote state
2. Configure Terraform to use remote state
3. Confirm that the state was successfully pushed, and that a copy exists in .terraform
4. Remove the local state files.

### Configuration example

```bash
terraform remote config -backend=s3 \
  -backend-config="bucket=myproject-terraform-state" \
  -backend-config="key=myproject/terraform.tfstate" \
  -backend-config="region=us-east-1"
```

## Versions
- terraform-inventory version '0.6.1'
- Terraform v0.7.0

## Additional information
Remote state include a `remote` block to preserve the remote configuration. This seems to cause no issues for terraform-inventory. I can confirm that terraform-inventory reads the file just fine.

**Comment by adammck** [comment]
Thanks for the detailed feature request. This is a fantastic idea, which I've taken a stab at in #41. Would you mind taking a look and letting me know if it works for you?

**Comment by cbarbour** [comment]
Awesome, thanks! I'll try it today and send my feedback.

**Comment by cbarbour** [comment]
The pull request did exactly what I was hoping for. Thanks!
