### ISSUE TITLE
Add support for reading multiple state files

### ISSUE THREAD

**Issue by spkane** [adammck/terraform-inventory#61]
It isn't uncommon for people to have multiple environments in terraform, but want to present a single inventory to ansible.

It would be useful to be able to read multiple state files and then merge the results into a single inventory.

**Comment by danlamanna** [comment]
I don't think the desired behavior should be to merge the results into a single inventory. Wouldn't it be better for terraform-inventory to only present the inventory for the currently selected env? Given some pointers I might be able to take a stab at this.

**Comment by danlamanna** [comment]
Looking at this more closely, it seems as though Terraform just stores the current environment name in a file - so the desired behavior I mentioned above should be pretty trivial to add. Should I submit a PR?

**Comment by adammck** [comment]
PRs are always welcome.

**Comment by spkane** [comment]
I actually ended up forking this project ( https://github.com/mantl/terraform.py ) for my needs, since it already supported multiple state files.

That being said, it would likely still be a nice improvement to the work here as well.
