### ISSUE TITLE
Digital Ocean?

### ISSUE THREAD

**Issue by rossedman** [adammck/terraform-inventory#7]
Does this work with Digital Ocean? Would love to see that happen. I currently am running some janky shells scripts to get Terraform and Ansible to play nicely.

**Comment by adammck** [comment]
I just released [v0.4](https://github.com/adammck/terraform-inventory/releases/tag/v0.4), with DigitalOcean support. I'd be very grateful if you could give it a try with your deployment, and let me know how it works out for you.

**Comment by rossedman** [comment]
@adammck Oh awesome! Do you have any examples or does it work just the same as what you have shown?

**Comment by rossedman** [comment]
@adammck Couldn't even get the app to work. Ansible keeps claiming there is no inventory file. I have tried everything in the docs as well as trying different flags and couldn't get a response. Any ideas? I do have a terraform.tfstate file in the directory as well.
